apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "chatbot.name" . }}
  labels:
    {{- include "labels.base" . | nindent 4 }}
    {{- include "labels.component" "chatbot" | nindent 4 }}
    {{- include "labels.version" . | nindent 4 }}
spec:
  replicas: {{ .Values.chatbot.replicaCount }}
  selector:
    matchLabels:
      {{- include "labels.base" . | nindent 6 }}
      {{- include "labels.component" "chatbot" | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "labels.base" . | nindent 8 }}
        {{- include "labels.component" "chatbot" | nindent 8 }}
        {{- include "labels.version" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "chatbot.name" . }}
      containers:
        - name: chatbot
          image: {{ .Values.chatbot.image.repository }}:{{ .Values.chatbot.image.tag }}
          imagePullPolicy: {{ .Values.chatbot.image.pullPolicy }}
          args:
            - --namespace={{ .Release.Namespace }}
          ports:
            - containerPort: {{ .Values.chatbot.service.internalPort }}
          resources:
            {{- toYaml .Values.chatbot.resources | nindent 12 }}
