kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "chatbot.name" . }}
  labels:
    {{- include "labels.base" . | nindent 4 }}
    {{- include "labels.component" "chatbot" | nindent 4 }}
    {{- include "labels.version" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "chatbot.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "chatbot.name" . }}
