kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "chatbot.name" . }}
  labels:
    {{- include "labels.base" . | nindent 4 }}
    {{- include "labels.component" "chatbot" | nindent 4 }}
    {{- include "labels.version" . | nindent 4 }}
