apiVersion: v1
kind: Service
metadata:
  name: {{ template "chatbot.name" . }}
  labels:
    {{- include "labels.base" . | nindent 4 }}
    {{- include "labels.component" "chatbot" | nindent 4 }}
    {{- include "labels.version" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.chatbot.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.chatbot.service.type }}
  ports:
  - port: {{ .Values.chatbot.service.externalPort }}
    targetPort: {{ .Values.chatbot.service.internalPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "labels.base" . | nindent 4 }}
    {{- include "labels.component" "chatbot" | nindent 4 }}
