package pluginimports

// We need to empty import all enabled plugins so that they will be linked into
// any hook binary.
import (
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/approve" // Import all enabled plugins.
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/assign"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/blockade"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/blunderbuss"
	_ "github.com/eddycharly/kloops/pkg/chatbot/plugins/branchcleaner"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/bugzilla"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/buildifier"
	_ "github.com/eddycharly/kloops/pkg/chatbot/plugins/cat"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/cherrypickunapproved"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/cla"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/dco"
	_ "github.com/eddycharly/kloops/pkg/chatbot/plugins/dog"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/golint"
	_ "github.com/eddycharly/kloops/pkg/chatbot/plugins/goose"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/heart"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/help"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/hold"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/invalidcommitmsg"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/label"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/lgtm"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/lifecycle"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/merge-method-comment"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/mergecommitblocker"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/milestone"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/milestoneapplier"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/milestonestatus"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/override"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/owners-label"
	_ "github.com/eddycharly/kloops/pkg/chatbot/plugins/pony"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/project"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/projectmanager"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/releasenote"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/require-matching-label"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/requiresig"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/retitle"
	_ "github.com/eddycharly/kloops/pkg/chatbot/plugins/shrug"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/sigmention"
	_ "github.com/eddycharly/kloops/pkg/chatbot/plugins/size"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/skip"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/slackevents"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/stage"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/trigger"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/updateconfig"
	// _ "github.com/eddycharly/kloops/pkg/chatbot/plugins/verify-owners"
	_ "github.com/eddycharly/kloops/pkg/chatbot/plugins/welcome"
	_ "github.com/eddycharly/kloops/pkg/chatbot/plugins/wip"
	_ "github.com/eddycharly/kloops/pkg/chatbot/plugins/yuks"
)
