name: Pull build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13
      - name: Checkout code
        uses: actions/checkout@v3.0.2
      - name: Go build
        run: TAG=$GITHUB_SHA make docker-build
