name: Push lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Fetch history
        run: git fetch --prune --unshallow
      - name: Lint
        uses: helm/chart-testing-action@v1.1.0
        with:
          command: lint
